name: Commit build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.events.commits.*.message), '[ci skip]')"
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: restore
      run: dotnet restore

    - name: pack packages
      run: "mkdir build && dotnet pack -p:SymbolPackageFormat=snupkg --include-source -o build -p:VersionSuffix='dev.${{ github.run_number }}' -p:BuildNumber=${{ github.run_number }}"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Starnight
        path: /home/runner/work/starnight/starnight/build/
    
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v4.0.0
      with:
        webhook-url: ${{ secrets.BUILD_WEBHOOK }}
        embed-title: New Starnight build available!
        embed-description: |
          Commit author: [${{ github.actor }}](https://github.com/${{ github.actor }})
          Commit hash: [`${{ github.sha }}`](https://github.com/${{github.repository}}/commit/${{github.sha}})
          GitHub Actions run: [${{ github.run_id }}](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
        embed-color: 6684774
    
    - name: Publish Dev Build
      run: "dotnet nuget push /home/runner/work/starnight/starnight/build/ -k ${{ secrets.NUGET_API_KEY }} -s NuGet --no-service-endpoint" # the -dev suffix will make it a pre-release by default