name: "Test Pull Request"

on:
  pull_request:

jobs:
  build_pr:
    runs-on: "ubuntu-latest"
    if: "!contains(toJSON(github.event.commits.*.message), '[ci-skip]')"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v4"
        with:
          dotnet-version: "7.0.0-preview.5.22303.8"

      - name: "Build PR"
        run: "dotnet build"