name: "Publish Starnight Release"

on:
  release:
    types: [ "published" ]

jobs:
  publish_release:

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v2"
        with:
          dotnet-version: 7.0.100-rc.2.22426.5
        
      - name: "Restore"
        run: "dotnet restore"

      - name: "Build Nuget Packages"
        run: "mkdir build && dotnet pack -p:SymbolPackageFormat=snupkg -p:Version=${{ github.event.release.tag_name }} -p:IncludeSymbols=true -p:IncludeSource=true -c Release -o build"

      - name: Publish main package
        run: "dotnet nuget push /home/runner/work/starnight/starnight/build/* --api-key ${{ secrets.NUGET_API_KEY }} --source NuGet --no-service-endpoint --skip-duplicate"
      
      - name: "Upload Nuget Packages To Github Release"
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
