name: "Publish Starnight Release"

on:
  release:
    types: [ "published" ]

jobs:
  publish_release:

    runs-on: "ubuntu-latest"
    if: "!contains(toJSON(github.event.commits.*.message), '[ci skip]')"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup .NET"
        uses: "actions/setup-dotnet@v1"
        with:
          dotnet-version: "7.0.0-preview2"

      - name: "Setup NuGet"
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: "Restore"
        run: "dotnet restore"

      - name: "Build Nuget Packages"
        run: "mkdir build && dotnet pack -p:SymbolPackageFormat=snupkg --include-source -c Release -o build"

      - name: Publish main package
        run: "nuget push /home/runner/work/starnight/starnight/build/Starnight.1.0.0-dev.${{ github.run_number }}.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source NuGet -NoServiceEndpoint"

      - name: Publish symbols package
        run: "nuget push /home/runner/work/starnight/starnight/build/Starnight.1.0.0-dev.${{ github.run_number }}.snupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source NuGet -NoServiceEndpoint"
      
      - name: "Upload Nuget Packages To Github Release"
        uses: "ncipollo/release-action@v1"
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true